build_from:
  aarch64: "homeassistant/aarch64-base-debian:bullseye"
  amd64: "homeassistant/amd64-base-debian:bullseye"
  armhf: "homeassistant/armhf-base-debian:bullseye"
  armv7: "homeassistant/armv7-base-debian:bullseye"
  i386: "homeassistant/i386-base-debian:bullseye"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Scrypted"
  org.opencontainers.image.description: "Scrypted is a home automation platform primarily focusing on making camera experiences seamless."
  org.opencontainers.image.source: "https://github.com/ggravlingen/ha-addon-scrypted"
  org.opencontainers.image.licenses: "Apache"
