build_from:
  aarch64: "homeassistant/aarch64-base-debian:bullseye"
  amd64: "homeassistant/amd64-base-debian:bullseye"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Scrypted"
  org.opencontainers.image.description: "Scrypted is a home automation platform primarily focusing on making camera experiences seamless."
  org.opencontainers.image.source: "https://github.com/ggravlingen/ha-addon-scrypted"
  org.opencontainers.image.licenses: "Apache"
  org.opencontainers.image.lib_version: 0.0.244
  org.opencontainers.image.version: 1.0.2
