name: Scrypted
version: "1.0.0"
slug: ggravlingen_scrypted
description: Add-on to run Scrypted, focusing on making camera experiences seamless
url: "https://github.com/ggravlingen/ha-addon-scrypted"
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:camera-wireless
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
hassio_api: true
